### 7장 텍스트 데이터 다루기

In [21]:
sentences = ['가장 자연스럽고 좋은 영화 였다','최고의 영화 4편이 기대됨','꿀잼 ','가장 핵노잼 최하점']

In [22]:
type(sentences),len(sentences)

(list, 4)

##### BOW(Bag of Words) 단어 가방으로 전처리

In [23]:
#420
from sklearn.feature_extraction.text import CountVectorizer # 갯수를 세어서 배열로 만든다

In [24]:
vect = CountVectorizer()

In [25]:
vect.fit(sentences)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [26]:
vect.vocabulary_

{'가장': 1,
 '자연스럽고': 6,
 '좋은': 7,
 '영화': 5,
 '였다': 4,
 '최고의': 8,
 '4편이': 0,
 '기대됨': 2,
 '꿀잼': 3,
 '핵노잼': 10,
 '최하점': 9}

In [27]:
#dense_matrix <-> sparse_matrix(자연어)  메모리 절약하기 위해 사용
sparse_matrix= vect.transform(sentences) # 자연어를 BOW로 변환
sparse_matrix 

<4x11 sparse matrix of type '<class 'numpy.int64'>'
	with 13 stored elements in Compressed Sparse Row format>

In [28]:
sparse_matrix.toarray() # sparse를 dense로 변환

array([[0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1]], dtype=int64)

In [29]:
sentences

['가장 자연스럽고 좋은 영화 였다', '최고의 영화 4편이 기대됨', '꿀잼 ', '가장 핵노잼 최하점']

In [30]:
from sklearn.datasets import fetch_20newsgroups 

In [32]:
news = fetch_20newsgroups() #Download진행됩니다.

In [37]:
len(news.data), len(news.target_names)

(11314, 20)

In [38]:
news.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [41]:
print(news.data[0])

From: lerxst@wam.umd.edu (where's my thing)
Subject: WHAT car is this!?
Nntp-Posting-Host: rac3.wam.umd.edu
Organization: University of Maryland, College Park
Lines: 15

 I was wondering if anyone out there could enlighten me on this car I saw
the other day. It was a 2-door sports car, looked to be from the late 60s/
early 70s. It was called a Bricklin. The doors were really small. In addition,
the front bumper was separate from the rest of the body. This is 
all I know. If anyone can tellme a model name, engine specs, years
of production, where this car is made, history, or whatever info you
have on this funky looking car, please e-mail.

Thanks,
- IL
   ---- brought to you by your neighborhood Lerxst ----







In [43]:
vect = CountVectorizer().fit(news.data)
# 자연어 뉴스그룹을 배열(vect)로 변환/BOW

In [46]:
len(vect.vocabulary_)

130107

In [47]:
sm = vect.transform(news.data)

In [48]:
sm

<11314x130107 sparse matrix of type '<class 'numpy.int64'>'
	with 1787565 stored elements in Compressed Sparse Row format>

In [49]:
from sklearn.linear_model import LogisticRegression

In [52]:
model = LogisticRegression().fit(sm, news.target)

C:\Users\wtime\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\wtime\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [53]:
model.score(sm, news.target)

0.999734841788934

In [73]:
test_set = ['Hi, Major League, who is winner?','I want to buy a notebook. where should I go?']

In [74]:
model.predict(vect.transform(test_set))

array([10,  4])

In [76]:
news.target_names[4]

'comp.sys.mac.hardware'

In [82]:
sm_test = vect.transform(test_set)
dm = sm_test[0].toarray()
dm.shape

(1, 130107)

In [84]:
sm_test[0].indices # indexes ㅂ열의 크기가 너무 크기 ㄸ문에 0이 아닌 값이 있는 위치를 볼 수 밖에 업습니다.

array([ 63092,  68532,  75022,  79043, 124147, 124501])

In [85]:
import konlpy

In [86]:
from konlpy.tag import Kkma
from konlpy.utils import pprint
kkma = Kkma()

C:\Users\wtime\Anaconda3\lib\site-packages\jpype\_core.py:210: UserWarning: 
-------------------------------------------------------------------------------
Deprecated: convertStrings was not specified when starting the JVM. The default
behavior in JPype will be False starting in JPype 0.8. The recommended setting
for new code is convertStrings=False.  The legacy value of True was assumed for
this session. If you are a user of an application that reported this warning,
please file a ticket with the developer.
-------------------------------------------------------------------------------

  """)


In [88]:
pprint(kkma.sentences(u'네,안녕하세요 반갑습니다.'))

['네, 안녕 하세요 반갑습니다.']


In [89]:
pprint(kkma.nouns(u'질문이나 건의사항은 깃헙 이슈 트래커에 남겨주세요.'))

['질문', '건의', '건의사항', '사항', '깃헙', '이슈', '트래커']


In [90]:
pprint(kkma.pos(u'오류보고는 실행환경, 에러메세지와함께 설명을 최대한상세히!^^'))

[('오류', 'NNG'),
 ('보고', 'NNG'),
 ('는', 'JX'),
 ('실행', 'NNG'),
 ('환경', 'NNG'),
 (',', 'SP'),
 ('에러', 'NNG'),
 ('메세지', 'NNG'),
 ('와', 'JKM'),
 ('함께', 'MAG'),
 ('설명', 'NNG'),
 ('을', 'JKO'),
 ('최대한', 'NNG'),
 ('상세히', 'MAG'),
 ('!', 'SF'),
 ('^^', 'EMO')]


In [92]:
#p445
from konlpy.tag import Okt
okt_tag = Okt()
okt_tag.morphs(u'질문이나 건의사항은 깃헙 이슈 트래커에 남겨주세요.')

['질문', '이나', '건의', '사항', '은', '깃', '헙', '이슈', '트래커', '에', '남겨주세요', '.']

In [98]:
cv = CountVectorizer(tokenizer=okt_tag.morphs) # 문장 > 벡터

In [104]:
sentences =['안녕. 나는 남자야 남자!','안녕. 나는 여자야 여자!!','안녕. 너는 민수야 민수!!!']

In [105]:
cv.fit(sentences) # 토큰을 다 잘라서 어휘 사전(vocaburary)를 준비합니다

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=<bound method Okt.morphs of <konlpy.tag._okt.Okt object at 0x00000238ABD779E8>>,
        vocabulary=None)

In [106]:
sparse_matrix = cv.transform(sentences)

In [107]:
sparse_matrix.toarray()

array([[1, 0, 0, 1, 1, 2, 0, 1, 0, 1, 1, 0],
       [0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 2],
       [0, 0, 1, 1, 0, 0, 1, 1, 2, 1, 1, 0]], dtype=int64)

In [108]:
cv.vocabulary_

{'안녕': 9,
 '.': 3,
 '나': 4,
 '는': 7,
 '남자': 5,
 '야': 10,
 '!': 0,
 '여자': 11,
 '!!': 1,
 '너': 6,
 '민수': 8,
 '!!!': 2}

네이버 영화리뷰

In [146]:
import pandas as pd

In [147]:
movie = pd.read_csv('ratings_train.txt', delimiter='\t')

In [148]:
movie.shape

(150000, 3)

In [149]:
movie.head()

id                                           document  label
0   9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1   3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [150]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 3 columns):
id          150000 non-null int64
document    149995 non-null object
label       150000 non-null int64
dtypes: int64(2), object(1)
memory usage: 3.4+ MB


In [151]:
movie = movie.drop(columns='id')

In [152]:
movie = movie.dropna()

In [153]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 149995 entries, 0 to 149999
Data columns (total 2 columns):
document    149995 non-null object
label       149995 non-null int64
dtypes: int64(1), object(1)
memory usage: 3.4+ MB


In [161]:
m = 5000
movie = movie.iloc[:m]

In [162]:
movie.head()

document  label
0                                아 더빙.. 진짜 짜증나네요 목소리      0
1                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2                                  너무재밓었다그래서보는것을추천한다      0
3                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [163]:
movie.isna().sum()

document    0
label       0
dtype: int64

In [164]:
x = movie.document # movie['document']
y = movie.label

In [165]:
import konlpy
from konlpy.tag import Kkma
from konlpy.utils import pprint
kkma = Kkma()

In [166]:
from konlpy.tag import Okt

In [196]:
cv = CountVectorizer(tokenizer=Okt().morphs,  ngram_range=(1, 2))

In [197]:
cv = cv.fit(x)

In [198]:
len(cv.vocabulary_)

62782

In [199]:
X_sm = cv.transform(x)

In [200]:
from sklearn.model_selection import cross_val_score

In [201]:
from sklearn.linear_model import LogisticRegression

In [202]:
score = cross_val_score(LogisticRegression(), X_sm, y)
score

C:\Users\wtime\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\wtime\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.76724655, 0.78764247, 0.77430972])

In [203]:
model = LogisticRegression().fit(X_sm, y)

In [206]:
sentences = ['두시간동안 잘 자고 나왔습니다','강력 수면제','돈이 너무 아까워요 ㅜㅜ', '너무 재밌어요','정말 재미 없지', '우디 수고했다. 새 삶 찾은거 축하하고 꼭 행복해라.']
model.predict(cv.transform(sentences))

array([0, 0, 0, 1, 0, 1], dtype=int64)